version: '3.3'

services:
  jdownloader:
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/London
       - UMASK_SET=022
     cap_add:
       - NET_ADMIN
     networks:
       - jdownloader_net
     devices:
       - "/dev/net/tun"
     dns:
       - 84.200.69.80
       - 84.200.70.40
     volumes:
       - ./openvpn:/etc/openvpn
       - ./download:/output:rw
     restart: always 
  jdownloader_proxy:
    image: nginx:1.19
    ports:
      - '5800:5800'
    depends_on:
      - jdownloader
    networks:
      - jdownloader_net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

networks:
  jdownloader_net:
    driver: bridge
